"""add heartbeat_at to image_builds and deployment_executions

Revision ID: 01350ebce389
Revises: 1268e9419f60
Create Date: 2026-08-11 12:43:18.280955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01350ebce389'
down_revision = '1268e9419f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Backfill any row that's already 'running' at migration time (a ghost
    # row wedged from before the reaper existed, or one genuinely mid-flight
    # right now) so it's immediately eligible for reaping instead of
    # surviving forever with heartbeat_at NULL — though the reaper's own
    # NULL-is-stale branch is sufficient on its own as a backstop even
    # without this backfill.
    op.execute("UPDATE image_builds SET heartbeat_at = started_at WHERE status = 'running'")
    op.execute("UPDATE deployment_executions SET heartbeat_at = started_at WHERE status = 'running'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_at')

    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.drop_column('heartbeat_at')

    # ### end Alembic commands ###
