"""add dockerfile model and builder dockerfile source

Revision ID: 039bae7c2bbf
Revises: 8467dc0ac6b0
Create Date: 2026-08-13 20:28:51.225672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039bae7c2bbf'
down_revision = '8467dc0ac6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dockerfiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builders', schema=None) as batch_op:
        # server_default so existing rows (this table already has data) get
        # a valid value instead of failing the NOT NULL constraint — matches
        # today's actual behavior for every pre-existing Builder (repo-path
        # Dockerfile, the only mode that existed before this migration).
        batch_op.add_column(sa.Column('dockerfile_source', sa.String(), nullable=False, server_default='repo'))
        batch_op.add_column(sa.Column('managed_dockerfile_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'dockerfiles', ['managed_dockerfile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('managed_dockerfile_id')
        batch_op.drop_column('dockerfile_source')

    op.drop_table('dockerfiles')
    # ### end Alembic commands ###
