"""add telegram bot commands enabled and last update id

Revision ID: 041a67231254
Revises: c5ebe879231b
Create Date: 2026-08-19 18:04:26.027822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041a67231254'
down_revision = 'c5ebe879231b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('telegram_bot_commands_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False)
        )
        batch_op.add_column(sa.Column('telegram_last_update_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('telegram_last_update_id')
        batch_op.drop_column('telegram_bot_commands_enabled')

    # ### end Alembic commands ###
