"""add discord bot integration fields

Revision ID: 0ac24b6bdb62
Revises: 77f615f52447
Create Date: 2026-09-08 12:34:26.431473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac24b6bdb62'
down_revision = '77f615f52447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        # server_default added by hand — Alembic's autogenerate doesn't
        # infer one from the model's Python-side default=False, and
        # system_configs already has an existing singleton row to backfill
        # (same fixup this repo's own telegram_notifications_enabled/
        # telegram_bot_commands_enabled migrations needed).
        batch_op.add_column(sa.Column('discord_notifications_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('encrypted_discord_bot_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('discord_bot_commands_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('discord_application_id', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_user_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('discord_user_id')

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('discord_application_id')
        batch_op.drop_column('discord_bot_commands_enabled')
        batch_op.drop_column('encrypted_discord_bot_token')
        batch_op.drop_column('discord_notifications_enabled')

    # ### end Alembic commands ###
