"""add hide_navbar_title_when_sidebar_open to system_configs

Revision ID: 128297392cfc
Revises: aa573230db0c
Create Date: 2026-08-07 18:48:19.216727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128297392cfc'
down_revision = 'aa573230db0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the already-existing singleton row (this
    # table predates this column, unlike every other NOT NULL boolean in
    # this schema, which was added as part of a brand-new table with no
    # existing rows to satisfy).
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'hide_navbar_title_when_sidebar_open',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('hide_navbar_title_when_sidebar_open')

    # ### end Alembic commands ###
