"""Add auto-generated build metadata fields to workflow steps

Revision ID: 12fa3cb1cfd5
Revises: 7d79f7acc529
Create Date: 2026-08-19 13:25:50.501904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fa3cb1cfd5'
down_revision = '7d79f7acc529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_step_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_bump_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('suggested_change_type_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('suggested_object_names', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('suggested_description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'change_types', ['suggested_change_type_id'], ['id'])

    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('auto_generate_build_metadata', sa.Boolean(), server_default=sa.text('false'), nullable=False)
        )
        batch_op.add_column(
            sa.Column('require_review_before_build', sa.Boolean(), server_default=sa.text('true'), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_column('require_review_before_build')
        batch_op.drop_column('auto_generate_build_metadata')

    with op.batch_alter_table('workflow_step_runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suggested_description')
        batch_op.drop_column('suggested_object_names')
        batch_op.drop_column('suggested_change_type_id')
        batch_op.drop_column('suggested_bump_type')

    # ### end Alembic commands ###
