"""Add security notification recipient to system config

Revision ID: 168112da5b63
Revises: 5c9ba2cb302e
Create Date: 2026-08-14 09:11:28.616056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168112da5b63'
down_revision = '5c9ba2cb302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_notification_user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['security_notification_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('security_notification_user_id')

    # ### end Alembic commands ###
