"""make deployment_executions.manifest_id nullable

Revision ID: 2864992eaa32
Revises: e57baba6abe0
Create Date: 2026-08-08 13:05:41.050650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2864992eaa32'
down_revision = 'e57baba6abe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.alter_column('manifest_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.alter_column('manifest_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
