"""add commit log limit to system config

Revision ID: 2a347cde1361
Revises: 4bec0353b1f9
Create Date: 2026-08-13 21:25:10.070997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a347cde1361'
down_revision = '4bec0353b1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        # server_default so the existing singleton row (this table already
        # has one) gets a valid value instead of failing the NOT NULL
        # constraint — matches the previously-hardcoded DEFAULT_LOG_LIMIT.
        batch_op.add_column(sa.Column('commit_log_limit', sa.Integer(), nullable=False, server_default='20'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('commit_log_limit')

    # ### end Alembic commands ###
