"""add app_base_url to system_configs

Revision ID: 3037a33b2e3e
Revises: 0ac24b6bdb62
Create Date: 2026-09-08 13:20:05.248889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3037a33b2e3e'
down_revision = '0ac24b6bdb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_base_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('app_base_url')

    # ### end Alembic commands ###
