"""add build_engine to system_configs

Revision ID: 3b0e9f838b4e
Revises: 1adfb697f81d
Create Date: 2026-08-07 08:02:32.575544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0e9f838b4e'
down_revision = '1adfb697f81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the one existing SystemConfig singleton row (if
    # any) so the NOT NULL constraint doesn't fail; dropped right after since
    # the app always inserts an explicit value (model-level default="docker").
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('build_engine', sa.String(), nullable=False, server_default='docker')
        )
        batch_op.alter_column('build_engine', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('build_engine')

    # ### end Alembic commands ###
