"""add group_name to builders

Revision ID: 3fbf9e010eb1
Revises: 80e119c75e04
Create Date: 2026-08-07 09:01:16.395753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbf9e010eb1'
down_revision = '80e119c75e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
