"""add version to version linking

Revision ID: 4bec0353b1f9
Revises: 039bae7c2bbf
Create Date: 2026-08-13 21:01:24.978883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bec0353b1f9'
down_revision = '039bae7c2bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_version_links',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('linked_version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['linked_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'linked_version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_version_links')
    # ### end Alembic commands ###
