"""add commit tracking to image builds

Revision ID: 526c1cd02a77
Revises: 01350ebce389
Create Date: 2026-08-13 14:05:01.479026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c1cd02a77'
down_revision = '01350ebce389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_build_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_build_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('author_email', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_build_id'], ['image_builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_sha', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.drop_column('commit_sha')

    op.drop_table('image_build_commits')
    # ### end Alembic commands ###
