"""Add login lockout, telegram integration, and password reset tokens

Revision ID: 5c9ba2cb302e
Revises: 2a347cde1361
Create Date: 2026-08-14 08:49:24.651395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9ba2cb302e'
down_revision = '2a347cde1361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_login_attempts', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('encrypted_telegram_bot_token', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('encrypted_telegram_bot_token')
        batch_op.drop_column('telegram_notifications_enabled')
        batch_op.drop_column('max_login_attempts')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
