"""add error_logs table

Revision ID: 6de15d4c3766
Revises: 8cd9ea7bfef1
Create Date: 2026-08-07 06:46:32.083301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de15d4c3766'
down_revision = '8cd9ea7bfef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version_links', schema=None) as batch_op:
        batch_op.create_check_constraint('ck_version_links_not_self', 'batch_id != linked_batch_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version_links', schema=None) as batch_op:
        batch_op.drop_constraint('ck_version_links_not_self', type_='check')

    op.drop_table('error_logs')
    # ### end Alembic commands ###
