"""add wait_for_ready_timeout_seconds to deployment_manifests

Revision ID: 77f615f52447
Revises: 041a67231254
Create Date: 2026-09-02 12:49:59.947103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f615f52447'
down_revision = '041a67231254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'wait_for_ready_timeout_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.drop_column('wait_for_ready_timeout_seconds')

    # ### end Alembic commands ###
