"""add error_log_id to image_builds

Revision ID: 7d79f7acc529
Revises: 168112da5b63
Create Date: 2026-08-18 13:16:19.134477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d79f7acc529'
down_revision = '168112da5b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_log_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'error_logs', ['error_log_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('error_log_id')

    # ### end Alembic commands ###
