"""defer batch version bump and stage documentation fields

Revision ID: 7f0d25e00255
Revises: 3fbf9e010eb1
Create Date: 2026-08-07 09:44:01.209418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0d25e00255'
down_revision = '3fbf9e010eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bumped_from_major', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bumped_from_minor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bumped_from_patch', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('object', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('change_type_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('additional_description', sa.Text(), nullable=True))
        batch_op.alter_column('full_version_string',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'change_types', ['change_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('full_version_string',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('additional_description')
        batch_op.drop_column('change_type_id')
        batch_op.drop_column('object')
        batch_op.drop_column('bumped_from_patch')
        batch_op.drop_column('bumped_from_minor')
        batch_op.drop_column('bumped_from_major')

    # ### end Alembic commands ###
