"""add image_name to builders

Revision ID: 80e119c75e04
Revises: 3b0e9f838b4e
Create Date: 2026-08-07 08:40:36.278534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e119c75e04'
down_revision = '3b0e9f838b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
