"""add object lookup table and many-to-many links

Revision ID: 8467dc0ac6b0
Revises: 526c1cd02a77
Create Date: 2026-08-13 14:13:18.065111

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8467dc0ac6b0'
down_revision = '526c1cd02a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('build_batch_objects',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['build_batches.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'object_id')
    )
    op.create_table('version_documentation_objects',
    sa.Column('version_documentation_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['version_documentation_id'], ['version_documentations.id'], ),
    sa.PrimaryKeyConstraint('version_documentation_id', 'object_id')
    )
    # ### end Alembic commands ###

    # --- hand-added data migration: turn every distinct existing free-text
    # `object` value (from both tables) into a real Object row, then link
    # whichever batches/version_documentations had it, before those columns
    # get dropped below. Exact-string dedup (not case-insensitive) — merging
    # differently-cased historical values could silently conflate things
    # that were meant to stay distinct.
    conn = op.get_bind()

    distinct_values = [
        row[0]
        for row in conn.execute(
            sa.text(
                "SELECT object FROM build_batches WHERE object IS NOT NULL "
                "UNION "
                "SELECT object FROM version_documentations WHERE object IS NOT NULL"
            )
        ).all()
    ]

    name_to_id = {}
    for name in distinct_values:
        object_id = str(uuid.uuid4())
        conn.execute(
            sa.text("INSERT INTO objects (id, name, is_active) VALUES (:id, :name, true)"),
            {"id": object_id, "name": name},
        )
        name_to_id[name] = object_id

    for batch_id, name in conn.execute(
        sa.text("SELECT id, object FROM build_batches WHERE object IS NOT NULL")
    ).all():
        conn.execute(
            sa.text("INSERT INTO build_batch_objects (batch_id, object_id) VALUES (:batch_id, :object_id)"),
            {"batch_id": batch_id, "object_id": name_to_id[name]},
        )

    for doc_id, name in conn.execute(
        sa.text("SELECT id, object FROM version_documentations WHERE object IS NOT NULL")
    ).all():
        conn.execute(
            sa.text(
                "INSERT INTO version_documentation_objects (version_documentation_id, object_id) "
                "VALUES (:doc_id, :object_id)"
            ),
            {"doc_id": doc_id, "object_id": name_to_id[name]},
        )

    with op.batch_alter_table('build_batches', schema=None) as batch_op:
        batch_op.drop_column('object')

    with op.batch_alter_table('version_documentations', schema=None) as batch_op:
        batch_op.drop_column('object')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: does not restore the original free-text values — a batch/doc
    # that ended up linked to more than one Object has no single string to
    # collapse back into, so downgrading loses that data rather than
    # guessing at a merge.
    with op.batch_alter_table('version_documentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('build_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('version_documentation_objects')
    op.drop_table('build_batch_objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
