"""add deployment_manifest allowed_users

Revision ID: 869fda148361
Revises: 2864992eaa32
Create Date: 2026-08-08 13:23:14.964740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869fda148361'
down_revision = '2864992eaa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_manifest_users',
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['deployment_manifests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('manifest_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_manifest_users')
    # ### end Alembic commands ###
