"""migrate to BuildBatch model structure

Revision ID: 8cd9ea7bfef1
Revises: aa6bc3a9f473
Create Date: 2026-08-06 18:19:45.330576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8cd9ea7bfef1'
down_revision = 'aa6bc3a9f473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=True),
    sa.Column('registry_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('version_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('git_source_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('local_path', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['git_source_id'], ['git_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_source_id', 'full_name', name='uq_repositories_source_full_name')
    )
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_type_id', sa.UUID(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_type_id'], ['version_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('build_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('full_version_string', sa.String(), nullable=False),
    sa.Column('bump_type', sa.String(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('builders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('dockerfile_path', sa.String(), nullable=False),
    sa.Column('registry_target_id', sa.UUID(), nullable=False),
    sa.Column('default_build_args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_target_id'], ['registry_targets.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('builder_configs')
    # build_versions is dropped after the batch_alter_table blocks below, since
    # image_builds/version_documentations/version_links still hold FKs into it
    # until those columns are dropped.
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('builder_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('branch_used', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('image_builds_requested_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('image_builds_version_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'builders', ['builder_id'], ['id'])
        batch_op.create_foreign_key(None, 'build_batches', ['batch_id'], ['id'])
        batch_op.drop_column('build_args')
        batch_op.drop_column('dockerfile_path')
        batch_op.drop_column('requested_by')
        batch_op.drop_column('version_id')
        batch_op.drop_column('repo_url')

    with op.batch_alter_table('version_documentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('version_documentations_version_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['batch_id'])
        batch_op.drop_constraint(batch_op.f('version_documentations_version_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'build_batches', ['batch_id'], ['id'])
        batch_op.drop_column('branch_name')
        batch_op.drop_column('version_id')

    with op.batch_alter_table('version_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('linked_batch_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_version_links_pair'), type_='unique')
        batch_op.create_unique_constraint('uq_version_links_pair', ['batch_id', 'linked_batch_id'])
        batch_op.drop_constraint(batch_op.f('version_links_linked_version_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('version_links_version_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'build_batches', ['linked_batch_id'], ['id'])
        batch_op.create_foreign_key(None, 'build_batches', ['batch_id'], ['id'])
        batch_op.drop_column('linked_version_id')
        batch_op.drop_column('version_id')

    op.drop_table('build_versions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # build_versions must exist before the batch_alter_table blocks below can
    # re-add FKs pointing into it.
    op.create_table('build_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('major', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime_string', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('full_version_string', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_branch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_commit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('commit_messages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('build_versions_pkey')),
    sa.UniqueConstraint('full_version_string', name=op.f('build_versions_full_version_string_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('version_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('linked_version_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('version_links_version_id_fkey'), 'build_versions', ['version_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('version_links_linked_version_id_fkey'), 'build_versions', ['linked_version_id'], ['id'])
        batch_op.drop_constraint('uq_version_links_pair', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_version_links_pair'), ['version_id', 'linked_version_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('linked_batch_id')
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('version_documentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('version_documentations_version_id_fkey'), 'build_versions', ['version_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('version_documentations_version_id_key'), ['version_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dockerfile_path', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('build_args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('image_builds_version_id_fkey'), 'build_versions', ['version_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('image_builds_requested_by_fkey'), 'users', ['requested_by'], ['id'])
        batch_op.drop_column('branch_used')
        batch_op.drop_column('builder_id')
        batch_op.drop_column('batch_id')

    op.create_table('builder_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('git_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('registry_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dockerfile_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_build_args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('repo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('builder_configs_pkey'))
    )
    op.drop_table('builders')
    op.drop_table('build_batches')
    op.drop_table('versions')
    op.drop_table('repositories')
    op.drop_table('version_types')
    op.drop_table('registry_targets')
    op.drop_table('git_sources')
    # ### end Alembic commands ###
