"""add repo_url to image_builds and builder_configs

Revision ID: 9041f792cd76
Revises: afe8ec6e49ed
Create Date: 2026-08-06 13:09:50.206039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9041f792cd76'
down_revision = 'afe8ec6e49ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builder_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_url', sa.String(), nullable=False))

    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.drop_column('repo_url')

    with op.batch_alter_table('builder_configs', schema=None) as batch_op:
        batch_op.drop_column('repo_url')

    # ### end Alembic commands ###
