"""add builder_roles table

Revision ID: aa573230db0c
Revises: 7f0d25e00255
Create Date: 2026-08-07 14:46:53.905885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa573230db0c'
down_revision = '7f0d25e00255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_roles',
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builders.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('builder_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builder_roles')
    # ### end Alembic commands ###
