"""add commit_messages to build_versions

Revision ID: aa6bc3a9f473
Revises: 9041f792cd76
Create Date: 2026-08-06 13:56:26.419721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6bc3a9f473'
down_revision = '9041f792cd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_messages', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build_versions', schema=None) as batch_op:
        batch_op.drop_column('commit_messages')

    # ### end Alembic commands ###
