"""add image builder models

Revision ID: afe8ec6e49ed
Revises: 219dbbafd41b
Create Date: 2026-08-06 12:41:09.314862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe8ec6e49ed'
down_revision = '219dbbafd41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_provider_configs_single_default', ['is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    op.create_table('build_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('datetime_string', sa.String(length=10), nullable=False),
    sa.Column('full_version_string', sa.String(), nullable=False),
    sa.Column('source_branch', sa.String(), nullable=False),
    sa.Column('source_commit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_version_string')
    )
    op.create_table('builder_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_provider', sa.String(), nullable=False),
    sa.Column('registry_provider', sa.String(), nullable=False),
    sa.Column('dockerfile_path', sa.String(), nullable=False),
    sa.Column('default_build_args', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_templates_single_default', ['is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    op.create_table('version_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('linked_version_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('version_id != linked_version_id', name='ck_version_links_not_self'),
    sa.ForeignKeyConstraint(['linked_version_id'], ['build_versions.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['build_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'linked_version_id', name='uq_version_links_pair')
    )
    op.create_table('image_builds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registry_name', sa.String(), nullable=True),
    sa.Column('image_tag', sa.String(), nullable=True),
    sa.Column('image_size', sa.BigInteger(), nullable=True),
    sa.Column('build_log', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('dockerfile_path', sa.String(), nullable=True),
    sa.Column('build_args', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['build_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.create_index('ix_image_builds_single_running', ['status'], unique=True, postgresql_where=sa.text("status = 'running'"))

    op.create_table('version_documentations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('built_by', sa.UUID(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('change_type_id', sa.UUID(), nullable=True),
    sa.Column('object', sa.String(), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_provider_used', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['built_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['change_type_id'], ['change_types.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['build_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_documentations')
    with op.batch_alter_table('image_builds', schema=None) as batch_op:
        batch_op.drop_index('ix_image_builds_single_running', postgresql_where=sa.text("status = 'running'"))

    op.drop_table('image_builds')
    op.drop_table('version_links')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_templates_single_default', postgresql_where=sa.text('is_default = true'))

    op.drop_table('prompt_templates')
    op.drop_table('change_types')
    op.drop_table('builder_configs')
    op.drop_table('build_versions')
    with op.batch_alter_table('ai_provider_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_provider_configs_single_default', postgresql_where=sa.text('is_default = true'))

    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
