"""Add is_active for archivable resources

Revision ID: c5ebe879231b
Revises: 12fa3cb1cfd5
Create Date: 2026-08-19 14:39:07.238198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ebe879231b'
down_revision = '12fa3cb1cfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('deployment_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('dockerfiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('git_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('registry_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versions', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('registry_targets', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('git_sources', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('dockerfiles', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('deployment_servers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('builders', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
