"""add deployment module models

Revision ID: dcedb8fa84b8
Revises: 128297392cfc
Create Date: 2026-08-07 19:52:59.113187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcedb8fa84b8'
down_revision = '128297392cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_manifests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_manifest_servers',
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['deployment_manifests.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['deployment_servers.id'], ),
    sa.PrimaryKeyConstraint('manifest_id', 'server_id')
    )
    op.create_table('deployment_server_roles',
    sa.Column('deployment_server_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_server_id'], ['deployment_servers.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('deployment_server_id', 'role_id')
    )
    op.create_table('deployment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('resolved_version_string', sa.Text(), nullable=True),
    sa.Column('rendered_yaml', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['deployment_manifests.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['deployment_runs.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['deployment_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.create_index('ix_deployment_executions_single_running', ['status'], unique=True, postgresql_where=sa.text("status = 'running'"))

    op.create_table('deployment_manifest_version_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manifest_id', sa.UUID(), nullable=False),
    sa.Column('placeholder_key', sa.String(), nullable=False),
    sa.Column('builder_id', sa.UUID(), nullable=False),
    sa.Column('pinned_image_build_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builders.id'], ),
    sa.ForeignKeyConstraint(['manifest_id'], ['deployment_manifests.id'], ),
    sa.ForeignKeyConstraint(['pinned_image_build_id'], ['image_builds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_id', 'placeholder_key', name='uq_deployment_binding_manifest_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_manifest_version_bindings')
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.drop_index('ix_deployment_executions_single_running', postgresql_where=sa.text("status = 'running'"))

    op.drop_table('deployment_executions')
    op.drop_table('deployment_runs')
    op.drop_table('deployment_server_roles')
    op.drop_table('deployment_manifest_servers')
    op.drop_table('deployment_servers')
    op.drop_table('deployment_manifests')
    # ### end Alembic commands ###
