"""add manifest order, run action, execution live-status, config interval

Revision ID: e57baba6abe0
Revises: dcedb8fa84b8
Create Date: 2026-08-08 11:38:50.540514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57baba6abe0'
down_revision = 'dcedb8fa84b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_execution_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('live_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('live_checked_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'deployment_executions', ['source_execution_id'], ['id'])

    # server_default backfills already-existing rows (this repo has a real
    # DeploymentManifest/Run/SystemConfig row from a prior session) — dropped
    # right after, same two-step pattern as
    # 3b0e9f838b4e_add_build_engine_to_system_configs.py.
    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.alter_column('order', server_default=None)

    with op.batch_alter_table('deployment_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(), nullable=False, server_default='deploy'))
    with op.batch_alter_table('deployment_runs', schema=None) as batch_op:
        batch_op.alter_column('action', server_default=None)

    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('deployment_status_check_interval_seconds', sa.Integer(), nullable=False, server_default='60')
        )
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.alter_column('deployment_status_check_interval_seconds', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('deployment_status_check_interval_seconds')

    with op.batch_alter_table('deployment_runs', schema=None) as batch_op:
        batch_op.drop_column('action')

    with op.batch_alter_table('deployment_manifests', schema=None) as batch_op:
        batch_op.drop_column('order')

    with op.batch_alter_table('deployment_executions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('live_checked_at')
        batch_op.drop_column('live_status')
        batch_op.drop_column('source_execution_id')

    # ### end Alembic commands ###
